twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'admin/form/content_type.html.twig'
        - 'form/custom_fields.html.twig'
when@test:
    twig:
        strict_variables: true
